import { spawn, spawnSync, type ChildProcess } from 'node:child_process'
import { createHash } from 'node:crypto'
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { afterEach, describe, expect, it, vi } from 'vitest'
import type { InterruptionFacts } from '../../scripts/restore-gate/deletion-proof-core'
import {
  INTERRUPT_SIGNALS,
  createInterruptionHandler,
  installInterruptionHandlers,
  interruptionSummary,
} from '../../scripts/restore-gate/interruption'

/**
 * P206: what happens when the owner-operated deletion proof is cancelled.
 *
 * The three cases the operator must be able to tell apart: cancelled BEFORE the delete request was
 * sent (nothing changed, safe to start again), the request SENT with no answer (outcome unknown -
 * never retry), and the answer received before the interruption. Everything here is mocked or runs
 * against a stand-in process: there is no Supabase project, no registry append or deletion, no
 * backup, and the stand-in's `fetch` is a tripwire that fails the test if an interruption touches
 * the network. Real signals are delivered to a real process (tests/ops/fixtures/interruption-child.ts,
 * which installs the SAME handler and summary builder as the tool).
 *
 * Platform limits, stated rather than papered over:
 *  - POSIX: SIGINT, SIGTERM and SIGHUP are delivered with kill(2) and all three are tested.
 *  - Windows: Node cannot send SIGINT to a child and `kill('SIGTERM')` terminates without a handler,
 *    so those cannot be observed. The real Ctrl+C and Ctrl+Break console events are generated by
 *    tests/ops/fixtures/send-console-event.ps1 against a child that launch-in-new-console.ps1 gave
 *    its own hidden console (Node's `detached` means no console at all on Windows).
 *    Ctrl+C is undeliverable to a process tree that was started with Ctrl+C disabled; the test then
 *    SKIPS with that reason instead of passing. SIGHUP (console window closed) has no safe way to be
 *    generated from a test and is covered only at the unit level.
 */

const repoRoot = fileURLToPath(new URL('../../', import.meta.url))
const FIXTURE = join(repoRoot, 'tests/ops/fixtures/interruption-child.ts')
const SENDER = join(repoRoot, 'tests/ops/fixtures/send-console-event.ps1')
const LAUNCHER = join(repoRoot, 'tests/ops/fixtures/launch-in-new-console.ps1')
const isWindows = process.platform === 'win32'

// Canary values, assembled at run time so no secret-shaped literal sits in the repository (the CI
// secret scan reads every commit). They only need to be distinctive enough to grep for in output.
const canary = (name: string): string => ['canary', name, 'ZXQJ7781'].join('-')
const SECRETS = {
  ERASURE_OPERATOR_TOKEN: canary('operator'),
  ERASURE_REGISTRY_KEY: canary('registry'),
  PP_SUPABASE_PUBLISHABLE_KEY: canary('publishable'),
}

const PHASES = {
  'before-send': {
    says: 'CANCELLED BEFORE THE DELETION REQUEST WAS SENT',
    forbids: [/DO NOT RUN/, /OUTCOME IS UNKNOWN/],
    sent: false,
    deleted: false,
  },
  'outcome-unknown': {
    says: 'THE OUTCOME IS UNKNOWN',
    forbids: [/safe to start the tool again/, /nothing was changed/i],
    sent: true,
    deleted: false,
  },
  'after-answer': {
    says: 'ANSWERED AS DELETED',
    forbids: [/safe to start the tool again/, /nothing was changed/i],
    sent: true,
    deleted: true,
  },
} as const
type Phase = keyof typeof PHASES

// ---------------------------------------------------------------------------------------------
// In-process: the handler with fake dependencies
// ---------------------------------------------------------------------------------------------

describe('interruption handler (no process, no signals)', () => {
  const answer = { requestSent: true, requestAnswered: true, deleted: false }

  function harness(facts: () => InterruptionFacts, persistThrows = false) {
    const stderr: string[] = []
    const persisted: unknown[] = []
    const exits: number[] = []
    const handler = createInterruptionHandler({
      facts,
      writeStderr: (text) => stderr.push(text),
      persist: (report) => {
        if (persistThrows) throw new Error('disk full')
        persisted.push(report.phase)
      },
      exit: (code) => {
        exits.push(code)
        throw new Error('exit') // stands in for process.exit, which never returns
      },
    })
    const fire = (): void => {
      try {
        handler()
      } catch (error) {
        if ((error as Error).message !== 'exit') throw error
      }
    }
    return { fire, stderr, persisted, exits }
  }

  afterEach(() => {
    vi.unstubAllGlobals()
  })

  it.each(Object.keys(PHASES) as Phase[])(
    '%s: one message, one summary, one exit (130)',
    (phase) => {
      const facts: InterruptionFacts =
        phase === 'before-send'
          ? { requestSent: false, requestAnswered: false, deleted: false }
          : phase === 'outcome-unknown'
            ? { requestSent: true, requestAnswered: false, deleted: false }
            : { requestSent: true, requestAnswered: true, deleted: true }
      const h = harness(() => facts)
      h.fire()
      expect(h.exits).toEqual([130])
      expect(h.persisted).toEqual([phase])
      expect(h.stderr).toHaveLength(1)
      expect(h.stderr[0]).toContain(PHASES[phase].says)
      for (const forbidden of PHASES[phase].forbids) expect(h.stderr[0]).not.toMatch(forbidden)
    },
  )

  it('is idempotent: a second signal exits at once and writes nothing twice', () => {
    const h = harness(() => answer)
    h.fire()
    h.fire()
    h.fire()
    expect(h.exits).toEqual([130, 130, 130])
    expect(h.stderr).toHaveLength(1)
    expect(h.persisted).toHaveLength(1)
  })

  it('reads the facts when the signal arrives, not when the handler was created', () => {
    const facts: InterruptionFacts = { requestSent: false, requestAnswered: false, deleted: false }
    const h = harness(() => facts)
    facts.requestSent = true // the request left after the handler was installed
    h.fire()
    expect(h.stderr[0]).toContain('THE OUTCOME IS UNKNOWN')
  })

  it('still exits, with the message already written, when the summary cannot be saved', () => {
    const h = harness(() => answer, true)
    h.fire()
    expect(h.exits).toEqual([130])
    expect(h.stderr).toHaveLength(1)
  })

  it('never touches the network, whatever the phase', () => {
    const fetchSpy = vi.fn()
    vi.stubGlobal('fetch', fetchSpy)
    for (const facts of [
      { requestSent: false, requestAnswered: false, deleted: false },
      { requestSent: true, requestAnswered: false, deleted: false },
      answer,
    ]) {
      harness(() => facts).fire()
    }
    expect(fetchSpy).not.toHaveBeenCalled()
  })

  it('registers exactly SIGINT, SIGTERM, SIGHUP and SIGBREAK, all on the one handler', () => {
    const registered = new Map<string, unknown>()
    const fake = {
      on(signal: string, listener: unknown) {
        registered.set(signal, listener)
        return this
      },
    }
    const handler = (): never => {
      throw new Error('unused')
    }
    installInterruptionHandlers(handler, fake as unknown as Pick<NodeJS.Process, 'on'>)
    expect([...registered.keys()].sort()).toEqual(['SIGBREAK', 'SIGHUP', 'SIGINT', 'SIGTERM'])
    expect(new Set(registered.values())).toEqual(new Set([handler]))
    expect([...INTERRUPT_SIGNALS].sort()).toEqual(['SIGBREAK', 'SIGHUP', 'SIGINT', 'SIGTERM'])
  })

  it('the summary is a fixed set of fields: no id, token, address or response content', () => {
    const report = { phase: 'outcome-unknown' as const, exitCode: 130, lines: [] as string[] }
    const summary = interruptionSummary(
      { requestSent: true, requestAnswered: false, deleted: false },
      report,
      [{ gate: 'a gate', pass: true }],
    )
    expect(Object.keys(summary).sort()).toEqual([
      'deleted',
      'deletionRequestSent',
      'interrupted',
      'results',
      'stopped',
    ])
  })
})

describe('the tool routes every interruption path through the shared handler', () => {
  const source = readFileSync(
    join(repoRoot, 'scripts/restore-gate/owner-deletion-proof.ts'),
    'utf8',
  )
  const module = readFileSync(join(repoRoot, 'scripts/restore-gate/interruption.ts'), 'utf8')

  it('installs the handler for every signal and uses it for the raw-mode Ctrl+C byte', () => {
    expect(source).toContain('createInterruptionHandler')
    expect(source).toContain('installInterruptionHandlers(handleInterruption)')
    expect(source).toMatch(/ch === '\\u0003'[\s\S]{0,120}handleInterruption\(\)/)
    expect(source).toContain('interruptionSummary(state, report, results)')
  })

  it('has no bare exit left that would be a silent path', () => {
    expect(source).not.toMatch(/process\.exit\(130\)/)
    expect(source.match(/process\.exit\(/g)).toHaveLength(1) // only the handler's own exit
  })

  it('the shared module is the only place a report is built, and has no network or registry access', () => {
    expect(module).toContain('describeInterruption')
    expect(module).not.toMatch(/fetch\(|createClient|exportRegistry|RegistryStore|appendFile/)
  })
})

// ---------------------------------------------------------------------------------------------
// Real process, real signals
// ---------------------------------------------------------------------------------------------

interface Child {
  pid: number
  outDir: string
  stdout: () => string
  stderr: () => string
  ready: () => Promise<void>
  /** Resolves with the status the fixture exited with, or rejects when it is still alive at `ms`. */
  exited: (ms: number) => Promise<number>
  /** True once the process is gone (Windows tests: the only portable liveness check). */
  kill: () => void
}

const dirs: string[] = []
const killers: (() => void)[] = []

afterEach(() => {
  for (const kill of killers.splice(0)) kill()
  for (const dir of dirs.splice(0)) rmSync(dir, { recursive: true, force: true })
})

const sleep = (ms: number): Promise<void> => new Promise((resolve) => setTimeout(resolve, ms))

function alive(pid: number): boolean {
  try {
    process.kill(pid, 0)
    return true
  } catch {
    return false
  }
}

async function until(condition: () => boolean, ms: number, what: string): Promise<void> {
  const deadline = Date.now() + ms
  while (!condition()) {
    if (Date.now() > deadline) throw new Error(`${what} did not happen within ${String(ms)} ms`)
    await sleep(50)
  }
}

/** POSIX: a plain child process with pipes. */
function startPosix(phase: Phase): Child {
  const outDir = mkdtempSync(join(tmpdir(), 'p206-interrupt-'))
  dirs.push(outDir)
  const proc: ChildProcess = spawn(process.execPath, ['--import', 'tsx', FIXTURE, phase, outDir], {
    cwd: repoRoot,
    env: { ...process.env, ...SECRETS },
    stdio: ['ignore', 'pipe', 'pipe'],
  })
  let out = ''
  let err = ''
  let status: number | null = null
  proc.stdout?.on('data', (d: Buffer) => (out += d.toString('utf8')))
  proc.stderr?.on('data', (d: Buffer) => (err += d.toString('utf8')))
  proc.on('exit', (code) => {
    status = code ?? -1
  })
  const kill = (): void => {
    if (status === null) proc.kill('SIGKILL')
  }
  killers.push(kill)
  return {
    pid: proc.pid as number,
    outDir,
    stdout: () => out,
    stderr: () => err,
    ready: () => until(() => out.includes('READY'), 60_000, 'the fixture becoming ready'),
    exited: async (ms) => {
      await until(() => status !== null, ms, 'the exit after the signal')
      return status as unknown as number
    },
    kill,
  }
}

/** Windows: the fixture runs in its own hidden console so a console control event can reach it. */
async function startWindows(phase: Phase): Promise<Child> {
  const outDir = mkdtempSync(join(tmpdir(), 'p206-interrupt-'))
  dirs.push(outDir)
  // stdio is not piped: the console child inherits the launcher's handles, and a pipe it holds open
  // would keep a synchronous spawn waiting until its timeout. The PID comes back through a file.
  const launcher = spawn(
    'powershell.exe',
    [
      '-NoProfile',
      '-ExecutionPolicy',
      'Bypass',
      '-File',
      LAUNCHER,
      '-Node',
      process.execPath,
      '-Fixture',
      FIXTURE,
      '-Phase',
      phase,
      '-OutDir',
      outDir,
      '-WorkDir',
      repoRoot,
    ],
    { env: { ...process.env, ...SECRETS }, windowsHide: true, stdio: 'ignore' },
  )
  killers.push(() => {
    if (launcher.exitCode === null) launcher.kill()
  })
  const pidFile = join(outDir, 'pid.txt')
  await until(() => existsSync(pidFile), 60_000, 'the launcher reporting the fixture PID')
  await sleep(100)
  const pid = Number(readFileSync(pidFile, 'utf8').trim())
  if (!Number.isInteger(pid) || pid <= 0) throw new Error('the launcher wrote no usable PID')
  const read = (name: string): string => {
    try {
      return readFileSync(join(outDir, name), 'utf8')
    } catch {
      return ''
    }
  }
  const kill = (): void => {
    if (alive(pid)) spawnSync('taskkill', ['/PID', String(pid), '/F'], { windowsHide: true })
  }
  killers.push(kill)
  return {
    pid,
    outDir,
    stdout: () => read('child.stdout.txt'),
    stderr: () => read('child.stderr.txt'),
    ready: () =>
      until(() => read('child.stdout.txt').includes('READY'), 60_000, 'the fixture becoming ready'),
    exited: async (ms) => {
      await until(() => !alive(pid), ms, 'the process ending after the console event')
      // The handler records the status it exits with just before process.exit.
      await until(() => read('exit-code.txt') !== '', 5_000, 'the exit status being recorded')
      return Number(read('exit-code.txt'))
    },
    kill,
  }
}

function assertInterrupted(child: Child, phase: Phase, exitCode: number): void {
  const expected = PHASES[phase]
  // Exit status: 128 + SIGINT, for every phase and every signal, so a wrapper can tell it from a failure.
  expect(exitCode).toBe(130)

  const stderr = child.stderr()
  expect(stderr).toContain(expected.says)
  for (const forbidden of expected.forbids) expect(stderr).not.toMatch(forbidden)
  expect(child.stdout().replace('READY', '').trim()).toBe('')

  const summaryText = readFileSync(join(child.outDir, 'p197b-result.json'), 'utf8')
  const summary = JSON.parse(summaryText) as Record<string, unknown>
  expect(Object.keys(summary).sort()).toEqual([
    'deleted',
    'deletionRequestSent',
    'interrupted',
    'results',
    'stopped',
  ])
  expect(summary).toMatchObject({
    stopped: true,
    interrupted: phase,
    deletionRequestSent: expected.sent,
    deleted: expected.deleted,
  })

  // No request and no retry: the stand-in's fetch tripwire was never hit.
  expect(existsSync(join(child.outDir, 'NETWORK_USED'))).toBe(false)
  // No registry append or deletion: the file the stand-in created is byte-identical.
  const registry = readFileSync(join(child.outDir, 'registry.ndjson'))
  expect(createHash('sha256').update(registry).digest('hex')).toBe(
    readFileSync(join(child.outDir, 'registry.sha256'), 'utf8'),
  )
  // Redaction: secrets present in the environment never reach an output or the summary.
  for (const secret of Object.values(SECRETS)) {
    expect(stderr).not.toContain(secret)
    expect(child.stdout()).not.toContain(secret)
    expect(summaryText).not.toContain(secret)
  }
  expect(summaryText).not.toMatch(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-/i)
  expect(summaryText).not.toMatch(/https?:\/\//)
}

describe.skipIf(isWindows)('real signals (POSIX)', () => {
  it.each(
    (Object.keys(PHASES) as Phase[]).flatMap((phase) =>
      (['SIGINT', 'SIGTERM', 'SIGHUP'] as const).map((signal) => [phase, signal] as const),
    ),
  )(
    '%s interrupted by %s',
    async (phase, signal) => {
      const child = startPosix(phase)
      await child.ready()
      process.kill(child.pid, signal)
      assertInterrupted(child, phase, await child.exited(20_000))
    },
    90_000,
  )
})

describe.skipIf(!isWindows)('real console control events (Windows)', () => {
  function sendConsoleEvent(pid: number, event: 'CtrlC' | 'CtrlBreak'): void {
    // Not awaited: the sender shares the target's console, so Ctrl+Break kills it too and its own
    // status means nothing. It is reaped with the other children after the test.
    const sender = spawn(
      'powershell.exe',
      [
        '-NoProfile',
        '-ExecutionPolicy',
        'Bypass',
        '-File',
        SENDER,
        '-TargetPid',
        String(pid),
        '-Event',
        event,
      ],
      { windowsHide: true, stdio: 'ignore' },
    )
    killers.push(() => {
      if (sender.exitCode === null) sender.kill()
    })
  }

  it.each(Object.keys(PHASES) as Phase[])(
    '%s interrupted by Ctrl+Break (SIGBREAK)',
    async (phase) => {
      const child = await startWindows(phase)
      await child.ready()
      sendConsoleEvent(child.pid, 'CtrlBreak')
      assertInterrupted(child, phase, await child.exited(20_000))
    },
    90_000,
  )

  it('Ctrl+C (SIGINT) is handled in every phase', async (ctx) => {
    for (const phase of Object.keys(PHASES) as Phase[]) {
      const child = await startWindows(phase)
      await child.ready()
      sendConsoleEvent(child.pid, 'CtrlC')
      await sleep(6_000)
      if (alive(child.pid)) {
        child.kill()
        ctx.skip(
          'Ctrl+C is disabled for this process tree (started with CREATE_NEW_PROCESS_GROUP), so ' +
            'SIGINT cannot be delivered from here; the Ctrl+Break tests above exercise the same handler',
        )
        return
      }
      assertInterrupted(child, phase, await child.exited(5_000))
    }
  }, 180_000)
})
