/// <reference types="vitest/config" />
import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

// Single source of truth for the app version shown in Profile's footer (M7.1 prompt §65) —
// package.json, not a hardcoded string that drifts from it.
const packageJson = JSON.parse(
  readFileSync(fileURLToPath(new URL('./package.json', import.meta.url)), 'utf-8'),
) as { version: string }

/**
 * Emits Cloudflare Pages' `_headers` file, with `connect-src` derived from the Supabase URL this
 * bundle was actually built against.
 *
 * Generated rather than checked in, for one reason: a hand-written CSP naming a project ref goes
 * stale the moment the app is pointed at a different Supabase project, and it goes stale silently
 * until someone opens the deployed app and finds every request blocked. M4 lost a day to exactly
 * that class of bug — configuration that was correct where it was written and wrong where it ran.
 * Deriving it from `VITE_SUPABASE_URL` means the policy and the client cannot disagree.
 *
 * `_headers` is ignored by `vite dev` and `vite preview`; only Cloudflare Pages reads it. So the
 * policy is exercised on the deployment and nowhere else, and has to be verified there.
 */
function cloudflareHeaders(): Plugin {
  return {
    name: 'pokeportfolio:cloudflare-headers',
    apply: 'build',
    generateBundle() {
      const supabaseUrl = process.env.VITE_SUPABASE_URL
      if (!supabaseUrl) {
        throw new Error(
          'VITE_SUPABASE_URL must be set at build time: the Content-Security-Policy in _headers ' +
            'is derived from it.',
        )
      }
      const origin = new URL(supabaseUrl).origin
      const realtime = origin.replace(/^http/, 'ws')

      const csp = [
        // Nothing loads from anywhere by default; every allowance below is deliberate.
        "default-src 'self'",
        // The build emits module scripts as files and no inline script — verified in dist. So this
        // needs no 'unsafe-inline' and no nonce, which is what makes the rest of the policy worth
        // having.
        "script-src 'self'",
        // 'unsafe-inline' is here for style *attributes*: AppShell sets safe-area padding with
        // `style={{ paddingTop: 'max(…, env(safe-area-inset-top))' }}`, which cannot be expressed
        // in a stylesheet. `style-src-attr` would express that precisely, but Safari support for it
        // is recent and iPhone is the primary platform — a policy that silently drops safe-area
        // padding on an older phone is worse than this allowance, which buys an attacker nothing
        // while script-src holds.
        "style-src 'self' 'unsafe-inline'",
        // M7 renders card artwork (search results, Portfolio grid tiles) from the TCGdex CDN
        // (docs/API_SOURCES.md) — named explicitly, not by loosening this to `https:`.
        "img-src 'self' data: blob: https://assets.tcgdex.net",
        "font-src 'self'",
        `connect-src 'self' ${origin} ${realtime}`,
        "manifest-src 'self'",
        "worker-src 'self'",
        "object-src 'none'",
        "base-uri 'self'",
        "form-action 'self'",
        "frame-ancestors 'none'",
        'upgrade-insecure-requests',
      ].join('; ')

      const headers = `# Generated by vite.config.ts. Do not edit by hand — edit the plugin.
#
# Cloudflare Pages applies these to static asset responses. There are no Pages Functions in this
# project; if one is ever added, note that custom headers do not apply to its responses.

/*
  Content-Security-Policy: ${csp}
  Referrer-Policy: no-referrer
  X-Content-Type-Options: nosniff
  Cross-Origin-Opener-Policy: same-origin
  Permissions-Policy: geolocation=(), microphone=(), payment=(), usb=()
  Strict-Transport-Security: max-age=31536000
`
      this.emitFile({ type: 'asset', fileName: '_headers', source: headers })
    },
  }
}

// https://vite.dev/config/
export default defineConfig({
  define: {
    __APP_VERSION__: JSON.stringify(packageJson.version),
  },
  plugins: [
    react(),
    tailwindcss(),
    cloudflareHeaders(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['icons/apple-touch-icon.png'],
      manifest: {
        name: 'PokePortfolio',
        short_name: 'PokePortfolio',
        description: 'A private Pokémon TCG collection and financial tracker.',
        theme_color: '#101113',
        background_color: '#101113',
        display: 'standalone',
        start_url: '/',
        scope: '/',
        icons: [
          { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          {
            src: '/icons/icon-512-maskable.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        // Precache the app shell only. Financial and auth data must never be
        // cached by the service worker — see docs/ARCHITECTURE.md §6.
        globPatterns: ['**/*.{js,css,html,svg,png,ico,woff2}'],
        navigateFallbackDenylist: [/^\/api\//],
      },
    }),
  ],
  test: {
    environment: 'node',
    // Infrastructure-free suites only. Database and authorization tests need a live Supabase
    // stack and run separately via `pnpm test:db` (vitest.db.config.ts) — see docs/TESTING.md §1.
    // tests/ui/ covers browser-platform logic that is pure enough to verify without a DOM
    // renderer (M13's file-delivery dispatch), with platform globals stubbed.
    include: ['tests/financial/**/*.test.ts', 'tests/data/**/*.test.ts', 'tests/ui/**/*.test.ts'],
    coverage: {
      provider: 'v8',
      include: ['src/domain/**/*.ts'],
    },
  },
})
