/**
 * Bounded cleanup of obsolete scanner Cache Storage entries (P87 F-42).
 *
 * WHY THIS EXISTS: P86's audit found that `vite.config.ts`'s runtime-caching comments claimed "an
 * abandoned old version simply ages out on devices," but `vite-plugin-pwa`'s
 * `cleanupOutdatedCaches` only prunes the Workbox PRECACHE, never named runtime caches like
 * `scanner-assets-v7`/`scanner-assets-visual-v1` — confirmed by reading its installed source.
 * Workbox's own `ExpirationPlugin` only prunes entries on cache reads/writes for THAT cache; once
 * a version bump ships and no route matches an old cache's prefix anymore, its own expiration
 * housekeeping stops running along with it. Old entries can persist well past the stated 90-day
 * policy on a device that jumps straight to a later version without ever hitting those routes
 * again.
 *
 * WHY MAIN-THREAD, NOT A SERVICE-WORKER `activate` HANDLER: this project's Service Worker is
 * generated by `vite-plugin-pwa`'s `generateSW` strategy (vite.config.ts), which does not expose a
 * seam for injecting custom `activate`-event logic without switching to the `injectManifest`
 * strategy — a materially larger, riskier change than this fix warrants. The Cache Storage API is
 * origin-scoped, not context-scoped: it is equally reachable from the page (`window`), the Service
 * Worker, and any dedicated Worker on the same origin. Running this cleanup once per app boot, from
 * the main thread, reaches the exact same cache entries an `activate` handler would.
 *
 * SCOPE: only cache names starting with a known scanner-cache PREFIX are ever considered, and only
 * those NOT in the current allowlist are deleted — this must never touch an unrelated application
 * cache (there are none today, but the check is prefix-scoped defensively regardless) or wipe
 * every cache on each visit. Never throws: Cache Storage can be unavailable (private-mode quirks,
 * an already-torn-down context) and a missing cleanup is never a reason to break app boot.
 */

/** Cache name prefixes this cleanup is allowed to ever consider deleting from. Anything NOT
 *  starting with one of these is left completely untouched, however unfamiliar its name. */
const SCANNER_CACHE_PREFIXES = ['scanner-assets-', 'scanner-visual-worker-cache-']

/**
 * Cache names currently in active use — kept as its own exported list (rather than re-deriving
 * from vite.config.ts, which this module must not import: that file is Node-only build
 * configuration, not shippable browser code) so a future cache-name bump is a one-line addition
 * here, reviewed alongside the rename itself.
 */
export const CURRENT_SCANNER_CACHE_NAMES: readonly string[] = [
  'scanner-assets-v7',
  'scanner-assets-visual-v1',
  'scanner-assets-visual-v1-index',
  'scanner-visual-worker-cache-v1',
]

function isScannerCacheName(name: string): boolean {
  return SCANNER_CACHE_PREFIXES.some((prefix) => name.startsWith(prefix))
}

/**
 * Deletes every Cache Storage entry whose name looks like a scanner cache (matches a known
 * prefix) but is not in {@link CURRENT_SCANNER_CACHE_NAMES}. Safe to call on every app boot —
 * idempotent (a clean device simply finds nothing to delete) and bounded (only ever touches
 * scanner-prefixed cache names). Never throws.
 */
export async function cleanupObsoleteScannerCaches(): Promise<{ deleted: readonly string[] }> {
  try {
    if (typeof caches === 'undefined') return { deleted: [] }
    const names = await caches.keys()
    const obsolete = names.filter(
      (name) => isScannerCacheName(name) && !CURRENT_SCANNER_CACHE_NAMES.includes(name),
    )
    for (const name of obsolete) {
      await caches.delete(name).catch(() => {
        // A single cache failing to delete (e.g. a concurrent open handle) must never abort the
        // rest of the cleanup or the app's own boot sequence.
      })
    }
    return { deleted: obsolete }
  } catch {
    return { deleted: [] }
  }
}
