import { createClient } from '@supabase/supabase-js'
import type { Database } from './database.types'

/**
 * The one Supabase client for the app. RLS is the actual access-control boundary (SECURITY.md
 * §2) — the anon key is public by design and grants nothing on its own.
 *
 * Parametrized with the generated `Database` type (database.types.ts, regenerated by
 * `pnpm db:types` in the same commit as any migration — DEVELOPMENT.md §4). Note that generated
 * `bigint` columns type as plain `number`, which is a boundary this project does not trust for
 * money — see src/data/money.ts. Typed query helpers/repositories arrive with the feature work
 * that needs them (M5+), per the "no placeholder repositories" rule in CLAUDE.md; this file is
 * only the client boundary M3 establishes.
 */

const url = import.meta.env.VITE_SUPABASE_URL as string | undefined
const publishableKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined

if (!url || !publishableKey) {
  throw new Error(
    'VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY must be set. Copy .env.example to ' +
      '.env.local and fill in the values from the Supabase project dashboard — see ' +
      'docs/DEVELOPMENT.md §2.',
  )
}

export const supabase = createClient<Database>(url, publishableKey)
